services:
  backend:
    build: 
      context: ./
    ports:
        - "3000:3000"
    environment:
      - POST=3000
      - DATABASE_URL=postgresql://postgres:test123@db:5432/mydb
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules

  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
